language: objective-c

osx_image: xcode8.3

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.coursier
  - $HOME/.sbt
  - platform
  - apps

install:
  - bin/prelude.sh

script:
  - bin/sbt-launch.sh clean test:compile test