version: 1.0.{build}

image: Visual Studio 2017

clone_folder: c:\sireum-v3

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64

cache:
  - '%APPVEYOR_BUILD_FOLDER%\platform'
  - '%APPVEYOR_BUILD_FOLDER%\apps'
  - '%USERPROFILE%\.m2'
  - '%USERPROFILE%\.ivy2'
  - '%USERPROFILE%\.coursier'

install:
  - set CI_TESTING=1
  - '%APPVEYOR_BUILD_FOLDER%\resources\appveyor\install.bat'

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\resources\appveyor\build.bat'

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\resources\appveyor\test.bat'
