version: 1.0.{build}

image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

clone_folder: c:\sireum-v3

before_build:
  - git submodule update -q --init --recursive

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64
  PATH: 'C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%'

cache:
  - platform -> bin\prelude.sh
  - apps -> bin\prelude.sh
  - '%USERPROFILE%\.ivy2'
  - '%USERPROFILE%\.coursier'
  - '%USERPROFILE%\.sbt'

install:
  - bash -lc "pacman --noconfirm -S unzip"
  - bash -lc "$APPVEYOR_BUILD_FOLDER/bin/prelude.sh"

build_script:
  - bash -lc "$APPVEYOR_BUILD_FOLDER/bin/sbt-launch.sh clean test:compile test:fastOptJS"

test_script:
  - bash -lc "$APPVEYOR_BUILD_FOLDER/bin/sbt-launch.sh -error test"
